receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 5s
  resourcedetection:
    detectors: [env, system]

exporters:
  debug:
    verbosity: detailed
  googlecloud:
    log:
      default_log_name: vanilla-opentelemetry-collector

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [debug, googlecloud]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, googlecloud]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, googlecloud]
