receivers:
  docker_stats:
    endpoint: "unix:///var/run/docker.sock"
    collection_interval: 15s

  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu:
      memory:
      disk:
      network:

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  filelog:
    include: [/var/lib/docker/containers/*/*.log]
    operators:
      - type: json_parser
        parse_from: body
      - type: move
        from: attributes.log
        to: body

processors:
  batch:
    timeout: 10s

exporters:
  debug:
    verbosity: basic
  googlecloud:
    log:
      default_log_name: opentelemetry-collector

service:
  pipelines:
    metrics:
      receivers: [docker_stats, hostmetrics, otlp]
      processors: [batch]
      exporters: [debug, googlecloud]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, googlecloud]
    logs:
      receivers: [filelog, otlp]
      processors: [batch]
      exporters: [debug, googlecloud]

